image: julia:0.6                # image comes from Docker hub

default:
  script:
    - julia test_script.jl
    - julia coverage_script.jl
#    - cd docs; julia -e "Pkg.add(\"Documenter\")"; julia --color=yes make.jl

pages:
  script:
    - julia -e "Pkg.add(\"Documenter\")"; julia --color=yes make.jl
  artifacts:
    paths:
      - docs/build
  only:
  - master
