image: julia:0.6                # image comes from Docker hub

default:
  script:
    - julia build_script.jl
    - julia -e "Pkg.test(\"GitlabJuliaDemo\"; coverage = true)"
    - julia coverage_script.jl

pages:
  stage: deploy
  script:
    - julia build_script.jl
    - julia -e "Pkg.add(\"Documenter\")"
    - ls -R                         # debug
    - git rev-parse --show-toplevel # debug
    - cd docs; julia --color=yes docs/make.jl; cd ..
    - mv docs/build public
    - ls -R                     # debug
  artifacts:
    paths:
      - public
  only:
  - master
