image: julia:0.6                # image comes from Docker hub

default:
  script:
    - julia build_script.jl
    - julia -e "Pkg.test(\"GitlabJuliaDemo\"; coverage = true)"
    - julia coverage_script.jl
#    - cd docs; julia -e "Pkg.add(\"Documenter\")"; julia --color=yes make.jl

pages:
  stage: deploy
  script:
    - julia build_script.jl
    - julia -e "Pkg.add(\"Documenter\")"
    - julia --color=yes docs/make.jl
  artifacts:
    paths:
      - docs/build
  only:
  - master
